# ------------------------------------------------------------
# In this file, you can make some modifications to the Streamlit
# app's global environment. 
#
# All of the possible config options can be found here:
# https://docs.streamlit.io/develop/api-reference/configuration/config.toml
# ------------------------------------------------------------


[client]
# Turning the default sidebar navigation off so we 
# can use our own
showSidebarNavigation = false
# Serve static files from the static directory
staticDirs = ["static"]

[theme]
# Setting some basic config options related to the theme of the app
base="light"
primaryColor="#6550e6"
font="sans serif"

[server]
runOnSave = true